version: '3'

services:

  database:
    image: 'mysql:latest'
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: dog_rest_app